Repository mozilla/fxa-shared, pull requests merged in 2018-07, with the labels that each got.

#29 feat(metrics): add event properties for email sender and service
  metrics/amplitude.js
  test/metrics/amplitude.js
Labels: waffle:review

#30 feat(metrics): Allow a function for `event` in the fuzzy types.
  metrics/amplitude.js
  test/metrics/amplitude.js
Labels: waffle:active

#31 chore(release): Bump to 1.0.12
  package.json
Labels: waffle:active

#21 feat(scope): Implement shareable code for checking OAuth scopes.
  .eslintrc
  README.md
  index.js
  l10n/localizeTimestamp.js
  metrics/amplitude.js
  oauth/scopes.js
  test/index.js
  test/l10n/localizeTimestamp.js
  test/metrics/amplitude.js
  test/oauth/scopes.js
Labels: train-116, waffle:active

#32 Merge v1.0.13 to master.
  package.json
Labels: waffle:review
